// Global configuration for the printable 28BYJ-48 Alt-Az mount.
// Units: millimetres, degrees.

$fn = $preview ? 48 : 96;
EPS = 0.02;

FIT = 0.25;
PRESS_FIT = 0.10;
ELEPHANT_FOOT = 0.25;
MIN_WALL = 2.4;

// 28BYJ-48 mechanical envelope. Clone dimensions vary: verify yours.
BYJ_BODY_D = 28.0;
BYJ_BODY_H = 19.0;
BYJ_FLANGE_T = 1.5;
BYJ_BOSS_D = 9.0;
BYJ_BOSS_H = 2.5;
BYJ_SHAFT_D = 5.0;
BYJ_SHAFT_FLAT = 3.0;
BYJ_SHAFT_L = 10.0;
BYJ_MOUNT_SPACING = 35.0;
BYJ_MOUNT_HOLE_D = 4.0;
BYJ_SHAFT_TO_HOLE_LINE = 8.0;
BYJ_BODY_CENTER_FROM_SHAFT = [0, -11.0];
BYJ_CABLE_BOX = [14.6, 8.0, 11.0];

// Additional reducer: 12 -> 48 and 12 -> 60 = 20:1.
GEAR_MODULE = 1.0;
GEAR_PRESSURE_ANGLE = 20;
GEAR_BACKLASH = 0.12;
GEAR_CLEARANCE = 0.25;
GEAR_Z1 = 12;
GEAR_Z2 = 48;
GEAR_Z3 = 12;
GEAR_Z4 = 60;
GEAR_FACE = 5.0;
GEAR_GAP = 1.0;
GEAR_STACK_H = GEAR_FACE * 2 + GEAR_GAP;
GEAR_RATIO = (GEAR_Z2 / GEAR_Z1) * (GEAR_Z4 / GEAR_Z3);
CD_STAGE1 = GEAR_MODULE * (GEAR_Z1 + GEAR_Z2) / 2;
CD_STAGE2 = GEAR_MODULE * (GEAR_Z3 + GEAR_Z4) / 2;

REDUCER_OUTPUT = [0, 0];
REDUCER_INTERMEDIATE = [CD_STAGE2, 0];
REDUCER_MOTOR = [CD_STAGE2, CD_STAGE1];
REDUCER_MOTOR_ROT = 130;
INTERMEDIATE_AXLE_D = 3.2;

BEARING_608_ID = 8.0;
BEARING_608_OD = 22.0;
BEARING_608_W = 7.0;
AXIS_SHAFT_D = 8.0;
AXIS_CLEARANCE_D = 8.3;
M3_CLEARANCE_D = 3.3;
M4_CLEARANCE_D = 4.4;
M5_CLEARANCE_D = 5.5;
M8_CLEARANCE_D = 8.6;

TRIPOD_THREAD_D = 6.35;
TRIPOD_CLEARANCE_D = 6.8;
TRIPOD_NUT_AF = 11.2;
TRIPOD_NUT_H = 5.8;

// Azimuth base, gearbox cover and turntable.
AZ_BASE_D = 132.0;
AZ_COVER_BOLT_R = 59.0;
AZ_BASE_PLATE_H = 3.0;
AZ_PEDESTAL_H = 24.0;
AZ_PEDESTAL_D = 48.0;
AZ_COVER_H = 16.0;
AZ_COVER_WALL = 3.0;
AZ_COVER_TOP_T = 3.0;
AZ_TURNTABLE_D = 120.0;
AZ_TURNTABLE_H = 9.0;
AZ_GLIDE_RADIUS = 43.0;
AZ_GLIDE_D = 8.0;
AZ_GLIDE_GAP = 1.0;
AZ_COVER_CLEARANCE = 0.8;
AZ_OUTPUT_SPACER_H = 5.0;
AZ_OUTPUT_PASSAGE_D = 32.0;
AZ_OUTPUT_LOCATOR_D = 30.0;
AZ_OUTPUT_LOCATOR_DEPTH = 2.0;
AZ_OUTPUT_BOLT_R = 11.5;
AZ_AXIS_NUT_RECESS_D = 17.0;
AZ_AXIS_NUT_RECESS_H = 4.0;
AZ_YOKE_MOUNT_X = 36.0;
AZ_YOKE_MOUNT_Y = 10.0;
AZ_YOKE_NUT_DEPTH = 3.5;

// Azimuth 20:1 printed reducer axial stack and interfaces.
AZ_GEAR_Z0 = 1.0;
AZ_UPPER_GEAR_Z = AZ_GEAR_Z0 + GEAR_FACE + GEAR_GAP;
AZ_GEAR_TOP_CLEARANCE = AZ_COVER_H - AZ_COVER_TOP_T - (AZ_UPPER_GEAR_Z + GEAR_FACE);
AZ_MOTOR_PINION_HUB_D = 10.8;
AZ_MOTOR_PINION_HUB_H = 7.0;
AZ_COMPOUND_HUB_D = 10.0;
AZ_INTERMEDIATE_BORE_D = 3.35;
AZ_OUTPUT_HUB_D = 29.6;
AZ_OUTPUT_HUB_H = AZ_COVER_H + AZ_GLIDE_GAP + AZ_OUTPUT_LOCATOR_DEPTH - AZ_UPPER_GEAR_Z;
AZ_OUTPUT_NUT_DEPTH = 2.8;

YOKE_AXIS_Z = 96.0;
YOKE_INNER_W = 92.0;
YOKE_ARM_T = 8.0;
YOKE_ARM_W = 34.0;
YOKE_OUTER_W = YOKE_INNER_W + 2 * YOKE_ARM_T;
YOKE_FOOT_LEN = 42.0;
YOKE_FOOT_W = 30.0;
YOKE_ARM_CENTER_X = YOKE_INNER_W / 2 + YOKE_ARM_T / 2;
YOKE_TENON_LEN = 28.0;
YOKE_BRIDGE_X = 112.0;
YOKE_BRIDGE_Y = 36.0;
YOKE_BRIDGE_H = 12.0;
YOKE_SLOT_DEPTH = 9.0;
YOKE_SLOT_CLEARANCE = 0.35;
YOKE_LOCK_LOCAL_Y = 3.0;
YOKE_BEARING_POCKET_DEPTH = 7.2;
YOKE_DRIVE_BOSS_D = 54.0;
YOKE_IDLER_BOSS_D = 44.0;
YOKE_GEARBOX_BOLT_R = 18.0;
ALT_GEARBOX_GAP = 14.0;
ALT_BACKPLATE_H = 3.2;
ALT_SHAFT_L = 165.0;

// Payload plate, split clamps and sliding 1/4-20 attachment.
PAYLOAD_PLATE = [80.0, 112.0, 6.0];
PAYLOAD_SLOT_L = 48.0;
PAYLOAD_SLOT_D = TRIPOD_CLEARANCE_D;
PAYLOAD_SLOT_CENTER_Y = 8.0;
PAYLOAD_SLIDER_TRAVEL = PAYLOAD_SLOT_L - PAYLOAD_SLOT_D;
PAYLOAD_SLIDER_MIN_Y = PAYLOAD_SLOT_CENTER_Y - PAYLOAD_SLIDER_TRAVEL / 2;
PAYLOAD_SLIDER_MAX_Y = PAYLOAD_SLOT_CENTER_Y + PAYLOAD_SLIDER_TRAVEL / 2;

SHAFT_CLAMP_W = 18.0;
SHAFT_CLAMP_L = 30.0;
SHAFT_CLAMP_H = 10.0;
PAYLOAD_CLAMP_LOWER_H = 8.0;
PAYLOAD_CLAMP_X = 27.0;
PAYLOAD_CLAMP_BOLT_Y = 10.0;

// Hand knob around the metal payload screw. The ribs extend beyond the 28 mm body.
CAMERA_KNOB_D = 28.0;
CAMERA_KNOB_H = 8.0;
CAMERA_KNOB_RIB_RADIAL_T = 2.4;
CAMERA_KNOB_ENVELOPE_D = CAMERA_KNOB_D + CAMERA_KNOB_RIB_RADIAL_T;
CAMERA_BOLT_HEAD_AF = 11.4;
CAMERA_BOLT_HEAD_H = 4.6;

// The knob/bolt adjustment assembly must clear the horizontal ALT shaft through
// the complete balancing-slot travel. Raising the plate through the upper clamp
// is preferable to sacrificing balance travel.
PAYLOAD_KNOB_SHAFT_CLEARANCE = 3.0;
PAYLOAD_CLAMP_UPPER_H = AXIS_SHAFT_D / 2 + PAYLOAD_KNOB_SHAFT_CLEARANCE + CAMERA_KNOB_H;
PAYLOAD_PLATE_Z = PAYLOAD_CLAMP_UPPER_H;
PAYLOAD_KNOB_Z = PAYLOAD_PLATE_Z - CAMERA_KNOB_H;
PAYLOAD_ADJUSTMENT_MIN_CLEARANCE = 2.0;
PAYLOAD_PLATE_OFFSET_Z = PAYLOAD_PLATE_Z;

// Altitude 20:1 drive, mounted outside yoke_arm_drive.
// Local gearbox coordinates are centered on the ALT shaft; +Z points outboard.
ALT_PLATE_T = 3.2;
ALT_OUTPUT_CENTER = [0, 0];
ALT_INTERMEDIATE = [CD_STAGE2, 0];
ALT_MOTOR = [CD_STAGE2, -CD_STAGE1];
ALT_MOTOR_ROT = 0;
ALT_GEAR_Z0 = ALT_PLATE_T + 1.0;
ALT_UPPER_GEAR_Z = ALT_GEAR_Z0 + GEAR_FACE + GEAR_GAP;
ALT_GUARD_H = 17.0;
ALT_GUARD_WALL = 2.4;
ALT_GUARD_TOP_T = 2.4;
ALT_GUARD_TOP_Z = ALT_PLATE_T + ALT_GUARD_H;
ALT_GEAR_TOP_CLEARANCE = ALT_GUARD_TOP_Z - ALT_GUARD_TOP_T - (ALT_UPPER_GEAR_Z + GEAR_FACE);
ALT_OUTLINE_R_OUTPUT = 36.0;
ALT_OUTLINE_R_INTERMEDIATE = 30.0;
ALT_OUTLINE_R_MOTOR = 25.0;
ALT_PLATE_OUTPUT_CLEAR_D = 24.0;
ALT_INTERMEDIATE_BORE_D = 3.35;
ALT_COMPOUND_HUB_D = 10.0;
ALT_MOTOR_PINION_HUB_D = 10.8;
ALT_OUTPUT_BORE_D = 8.20;
ALT_OUTPUT_HUB_D = 24.0;
ALT_OUTPUT_HUB_H = 15.0;
ALT_OUTPUT_SET_PILOT_D = 2.7;
ALT_OUTPUT_SET_Z = 11.2;
ALT_OUTPUT_SPACER_D = 12.0;
ALT_OUTPUT_SPACER_H = ALT_UPPER_GEAR_Z - 0.15;
ALT_GUARD_CENTER_CLEAR_D = 26.0;
ALT_GUARD_BOSS_H = 4.0;
ALT_GUARD_SCREW_POS = [[-30,-24],[-30,24],[62,22],[58,-44]];
ALT_GUARD_SCREW_BOSS_D = 10.0;
ALT_GUARD_NUT_DEPTH = 2.8;
ALT_YOKE_HEAD_RECESS_D = 6.4;
ALT_YOKE_HEAD_RECESS_H = 1.7;

// Removable tabletop adapter for flat-surface operation.
TABLETOP_BASE_D = 190.0;
TABLETOP_BASE_T = 8.0;
TABLETOP_LOCATOR_D = AZ_PEDESTAL_D + 1.0;
TABLETOP_LOCATOR_DEPTH = 1.5;
TABLETOP_CENTER_CLEAR_D = TRIPOD_CLEARANCE_D;
TABLETOP_BOLT_HEAD_D = 16.0;
TABLETOP_BOLT_HEAD_RECESS_H = 5.0;
TABLETOP_FOOT_R = 82.0;
TABLETOP_FOOT_D = 18.0;
TABLETOP_FOOT_RECESS_H = 1.2;

BYJ_NOMINAL_HALFSTEPS_PER_OUTPUT_REV = 4096;
AXIS_NOMINAL_STEPS_PER_REV = BYJ_NOMINAL_HALFSTEPS_PER_OUTPUT_REV * GEAR_RATIO;
